export const clientsConstants={
    FETCH_ALL_CLIENTS_BEGIN: 'FETCH_ALL_CLIENTS_BEGIN',
    FETCH_ALL_CLIENTS_SUCCESS:'FETCH_ALL_CLIENTS_SUCCESS',
    FETCH_ALL_CLIENTS_ERROR:'FETCH_ALL_CLIENTS_ERROR'
  };